### ISSUE TITLE
Copy to clipboard feature for social sharing modal.

### ISSUE THREAD

**Issue by adeekshith** [parishod/doc-viewer-api-interface#17]
Copy to clipboard button should be added along with the already existing social buttons.
Clicking on copy to clipboard button should copy to clipboard if possible and should also display text box filled with url and pre selected.

**Comment by adeekshith** [comment]
Uday, just checked 995748c. It looks like a good progress but sorry I actually meant little different. I wanted it beside facebook , twitter buttons in the same social sharing modal.

**Comment by adeekshith** [comment]
This is something which I had in mind but any better idea is appreciated.
Clicking on the clipboard button in "Share this page" modal will create a new textbox with the full document url (`document.location.href`) in highlighted mode. I do not know if JS can actually copy to the clipboard without flash. If there is a supported API, we also directly copy to clipboard and flash a message "Copied to clipboard".
![dov_6](https://cloud.githubusercontent.com/assets/2568945/13364350/f94920ea-dc93-11e5-88d2-1f33d20c8ceb.jpg)

**Comment by adeekshith** [comment]
Works great.
Minor improvements needed to resolve:
- Need to pass text by value to `copyTextToClipboard()` instead of assigning it inside the function as functions in libraries need to be independent of external values wherever possible.
- Code cleaning

**Comment by adeekshith** [comment]
Not working on Firefox. Not sure if it is general Firefox issue or specific to me.

**Comment by spuday90** [comment]
Yeah same issue with me also looks like setselection function is not working in firefox. With out selection the copy command doesnot work
